version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: apex
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: apexdigital
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  ai-microservice:
    build: ./ai-microservice
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  pgdata:
